name: Docker CI/CD

# Se definen los eventos que deben activar el flujo de trabajo.
on:
  push:
    branches:
      - main

# Se define el trabajo que debe realizarse
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    
    steps:
    # Git checkout
    - name: Checkout
      uses: actions/checkout@v2

    # Build image
    - name: Build image
      uses: docker/build-push-action@v1
      with:
        context: .

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push image to Docker Hub
    - name: Push image
      uses: docker/build-push-action@v1
      with:
        push: true
        context: .
        tags: taskmanager-mern-stack:latest

    # Deploy image
    #- name: Deploy
    #  uses: appleboy/ssh-action@master
     # with:
      #  host: ${{ secrets.SSH_HOST }}
       # username: ${{ secrets.SSH_USER }}
        #password: ${{ secrets.SSH_PASSWORD }}
        #script: |
         # docker pull your-docker-repo:latest
          #docker stop existing_container || true
          #docker rm existing_container || true
          #docker run -d --name your_container -p 80:80 your-docker-repo:latest
