name: Docker CI/CD

# Define events that start workflow
on:
  push:
    branches:
      - main

# define jobs to do
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build image and push
      - name: Build image and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: taskmanager-mern-stack:latest

    # Deploy image
    #- name: Deploy
    #  uses: appleboy/ssh-action@master
    # with:
    #  host: ${{ secrets.SSH_HOST }}
    # username: ${{ secrets.SSH_USER }}
    #password: ${{ secrets.SSH_PASSWORD }}
    #script: |
    # docker pull your-docker-repo:latest
    #docker stop existing_container || true
    #docker rm existing_container || true
    #docker run -d --name your_container -p 80:80 your-docker-repo:latest
